### ISSUE TITLE
Separate error message for incompatible sub

### ISSUE THREAD

**Issue by lionslancer** [joaquintorres/autosubsync-mpv#10]
When attempting to sync against an internal bitmap sub, the same error message is printed as if there had been no internal subs present at all. This happens because the sync engines are incompatible with bitmap subs. Adding a separate error message for incompatible sub types would signal to the user that the script is functioning properly and that they need to find a different subtitle. 

Something along the lines of `Couldn't extract internal subtitle. Internal subtitle filetype is incompatible.` instead of
`Couldn't extract internal subtitle. Make sure the video has internal subtitles.`

*Also, very minor detail, but changing `Sync to an internal subtitle` to simply `Sync to internal subtitle` causes to text to fully fit inside the textbox.

**Comment by tatsumoto-ren** [comment]
The text fits inside the box unless your font is wrong. 

I'll fix the rest when the ability to choose what track to retime against is implemented.

**Comment by lionslancer** [comment]
Sounds good. How do you plan to implement track selection? If you can choose between all currently loaded subs then that sounds like a good way of killing two birds and implementing #8. Are you looking at track selection for audio as well?

**Comment by tatsumoto-ren** [comment]
Yes, iterating through loaded tracks is the best way.

**Comment by tatsumoto-ren** [comment]
Should be fixed now.
