### ISSUE TITLE
Subtitle fails to sync

### ISSUE THREAD

**Issue by Zuchter** [joaquintorres/autosubsync-mpv#11]
I'm trying to sync a subtitle to a k-on episode that has internal subtitles, but it fails. I've tried the script before and it works with no issues on other k-on episodes. I use alass and Arch, dunno what might be causing the fail

**Comment by tatsumoto-ren** [comment]
This needs further investigation.

**Comment by Zuchter** [comment]
Any way I can help with debugging ?

**Comment by tatsumoto-ren** [comment]
Make sure you have `ffmpeg` and `ffsubsync` installed, and the add-on is configured. Then launch mpv from the terminal to see what it says in the logs.

**Comment by lionslancer** [comment]
Does the script fail to output at all, or does it output an unsynced file? The former could mean an unsupported subtitle type, the latter could mean that everything works as intended but something is preventing the files from synchronizing properly, such as one language having subbed OPs and EDs but not the other.

**Comment by Zuchter** [comment]
> Make sure you have `ffmpeg` and `ffsubsync` installed, and the add-on is configured. Then launch mpv from the terminal to see what it says in the logs.

I've only installed alass trough the [aur](https://aur.archlinux.org/packages/alass-git/), should I also install ffsubsync? 

I launched mpv with the video file trough the terminal and this is what I got : 

> [zuchter@cappy K-ON! Livehouse!]$ mpv '[ToishY] K-ON! Livehouse! - 01.mkv' 
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) 'FLAC' (flac 2ch 48000Hz)
     Audio --aid=2 --alang=jpn 'FLAC (commentary)' (flac 2ch 48000Hz)
     Audio --aid=3 --alang=jpn 'FLAC (commentary 2)' (flac 2ch 48000Hz)
     Subs  --sid=1 --slang=eng (*) 'English' (ass)
 (+) Subs  --sid=2 '[ToishY] K-ON! Livehouse! - 01.srt' (subrip) (external)
File tags:
 Title: [ToishY] K-ON! Livehouse!
AO: [pulse] 48000Hz stereo 2ch s32
VO: [gpu] 1920x1080 yuv420p
(Paused) AV: 00:00:02 / 00:23:41 (0%) A-V:  0.000
[autosubsync] Extracting internal subtitles... 
(Paused) AV: 00:00:02 / 00:23:41 (0%) A-V:  0.000
[autosubsync] Starting alass... 
(Paused) AV: 00:00:02 / 00:23:41 (0%) A-V:  0.000
[autosubsync] Subtitle synchronization failed. 
(Paused) AV: 00:00:02 / 00:23:41 (0%) A-V:  0.000

Mpv does not output any subtitle file after the synchronization fails, and the k on episode has both the op and ed subbed in english.

edit: I just noticed that the same thing happens on attack on titan s1 but the op/ed is not subbed in english (but the episode is)

**Comment by tatsumoto-ren** [comment]
> should I also install ffsubsync

Try it to see if it works.

**Comment by tatsumoto-ren** [comment]
I tried to reproduce your results but couldn't. `alass` works just fine with this add-on on my machine.

**Comment by lionslancer** [comment]
Do other files in the same release as the problematic files work properly? You mentioned other K-on episodes working, but are they from the same batch?

**Comment by Zuchter** [comment]
The K-on episode was from the same torrent

**Comment by Zuchter** [comment]
I installed ffsubsync trough the aur package and tried to sync the first episode of AOT and it worked just fine with ffsubsync! 

I also tried it on another aot episode and the k-on livehouse one and it works just fine. I'll close this issue
