### ISSUE TITLE
Possible redundant comment in Readme

### ISSUE THREAD

**Issue by arscynic** [joaquintorres/autosubsync-mpv#12]
> $ pip install ffsubsync
$ trizen -S alass-git # for Arch Linux users

I'm using EndeavourOS (Arch based), and the pip install works fine. I initially skipped it and went straight to trizen, but the command didn't get recognized. I'm opening this issue because the “# for Arch Linux users” comment might be confusing.

PS Amazing script, thank you.

**Comment by tatsumoto-ren** [comment]
The latter command works on any Arch-based GNU/Linux distro. But you need to have trizen installed, it's not installed out of the box. Intalling ffsubsync is usually enough to get the add-on working, alass is entirely optional.
