### ISSUE TITLE
Can't get the menu to show

### ISSUE THREAD

**Issue by KAELINS** [joaquintorres/autosubsync-mpv#13]
I've checked many times and "n" is not mapped to anything, tried mapping another key... but the menu never appears.

alass and ffsubsync and ffmpeg are installed and are present in system path as well as I have tried updating path in both the lua as well as conf, tried "\\ ", "/", "\" as path separators

Don't get any error message or indicator from the script, what am I doing wrong?

mpv 0.33.0-204-ga1c6762156

**Comment by tatsumoto-ren** [comment]
Make sure `autosubsync-mpv `  is installed properly. This is the expected content of your `~/.config/mpv/` directory:

```
|-- script-opts
|   `-- autosubsync.conf
` -- scripts
    ` -- autosubsync
        |-- autosubsync.lua
        |-- main.lua
        ` -- menu.lua
```

**Comment by KAELINS** [comment]
I have installed similarly:

![](https://i.imgur.com/solkrYD.png)

It seems it doesn't even recognize the shortcut (n), but I've tried changing that as well...
I have no issues using alass from cmd

Is there any way I can debug this in more detail?

**Comment by KAELINS** [comment]
btw I have tried removing all other scripts and running without conf file but still cant get the menu to show

**Comment by tatsumoto-ren** [comment]
It's not installed properly because you have all your scripts in one folder. If you put all autosubsync files in its own folder as the README suggests, it will work.

**Comment by KAELINS** [comment]
Thank you very much, I feel very specially stupid now for having missed that from your previous comments.
Have a nice day man!
