### ISSUE TITLE
ffsubsync unable to read reference http

### ISSUE THREAD

**Issue by Alistair1231** [joaquintorres/autosubsync-mpv#15]
I am getting this error.
```
[autosubsync] [22:16:08] ERROR    unable to read reference https://user: ffsubsync.py:387
[autosubsync]                     pass@website.com/T
[autosubsync]                     V/Star%20Trek%20The%20Next%20Generation/St
[autosubsync]                     ar.Trek.TNG.Season.2/Star.Trek.The.Next.Ge
[autosubsync]                     neration.S02E02.Where.Silence.Has.Lease.10
[autosubsync]                     80p.bluray.AAC.5.1.x265.mkv; try ensuring
[autosubsync]                     file exists and has correct permissions
[autosubsync] Subtitle synchronization failed.
```
Is it incompatible with URLs or is the issues something else? 
The subtitles are in a location like this:
`C:\Users\me\AppData\Local\Temp\Star.Trek.The.Next.Generation.S02E02.Where.Silence.Has.Lease.1080p.bluray.AAC.5.1.x265.nl.srt`

EDIT: I just tried ffsubsync by itself and it throws the same error. So not an issue of the script... 
This [oseiskar/autosubsync](https://github.com/oseiskar/autosubsync) works well! Could you add support for it? That would be greatly appreciated!

**Comment by tatsumoto-ren** [comment]
The most important rule is, "always download what you watch."

**Comment by Alistair1231** [comment]
well, it's hosted on a service I am paying for. Also that way I can save me the required storage space and it works flawlessly for playback.
But I guess if you have such strong opinions about it I will have to find a different solution.
Thanks for the work on the script and the participation in the foss community anyways.

**Comment by tatsumoto-ren** [comment]
It's alright, you can delete it after you finish watching to free space. It seems like this service of yours gives you direct links, and mpv is able to play them, so there's no obstacles to downloading the files.

**Comment by Alistair1231** [comment]
well, I prefer how I'm doing it right now. But I acknowledge that everyone has different preferences.
