### ISSUE TITLE
Unable to Extract Internal Subs

### ISSUE THREAD

**Issue by mariaWitch** [joaquintorres/autosubsync-mpv#16]
At least on Windows, when trying to extract internal subs with Alass, the plugin starts the process and then fails out saying that it could not find any external subs. It does not create any subfiles during this process. However, if you manually extract the subtitles and then retime them with the tool, it works fine.
![image](https://user-images.githubusercontent.com/77745122/158194790-36fcc403-1e03-43b6-b0d9-a227d61dddef.png)
(The above is an example of the type of output I am seeing.)

**Comment by tatsumoto-ren** [comment]
External subtitles are called external because they have to be present next to the video file, in the same folder. Autosubsync doesn't retime internal subtitles because they should be already timed.

**Comment by mariaWitch** [comment]
You already provide internal subtitle extraction for another part of the script. I fail to see why this isn't easily solved by using the same logic from there. You assume that they should already be timed, but there are edge cases that exist where they are not always timed properly. 

See: https://github.com/Ajatt-Tools/autosubsync-mpv/pull/5

**Comment by mariaWitch** [comment]
Resolved.
