### ISSUE TITLE
Support for external subtitle files.

### ISSUE THREAD

**Issue by lionslancer** [joaquintorres/autosubsync-mpv#8]
In situations where there are no internal subs available, synced external sub files are often easily available. Even when there are internal subs available, they're not always usable. I had an issue with what I assume to be bitmap DVD subs not being recognized.

The current workaround is to simply use `alass` or `ffsubsync` directly from the terminal to sync the file, but it would be convenient to have support for it in the script. My understanding is that the way the script deals with internal subs is to extract them and then feed them to `alass`/`ffs` as if they were external files, so based on that I don't think it would be that difficult to implement.

**Comment by tatsumoto-ren** [comment]
Should be fixed now.

**Comment by lionslancer** [comment]
First of all, thank you very much for implementing this, it's been very helpful already.

I caught a bug causing files to be deleted when I first tested it, but it seems like it's been solved in the most recent git version. Two minor nitpicks about the interface though:
- The sub track selection menu is currently a submenu of `Sync to an internal subtitle`, even when syncing to an external subtitle. Consider removing the word "internal" now that subs are are individually marked as internal or external.
- The numbering of subtitles is odd. With one internal subtitle and two external, they are numbered as `Internal #3`, `External #0`, `External #0`. I think the internal subtitle count may be including audio tracks, and all external subtitles seem to be numbered #0.

**Comment by tatsumoto-ren** [comment]
>  Consider removing the word "internal" 

Good idea. Removed.

> The numbering of subtitles is odd.

ff-index is used for internal subtitles. For external it's 0. Probably, removing the counter is the best option here.
