### ISSUE TITLE
Use different sync engine depending on reference.

### ISSUE THREAD

**Issue by lionslancer** [joaquintorres/autosubsync-mpv#9]
I ran some tests comparing how `alass` and `ffsubsync` perform using various options. What I noticed was that `alass` more consistently output correctly synced subs when syncing against a reference subtitle, while ´ffsubsync´ performed better than ´alass´ when syncing against audio. 

Given that the script already supports both engines, I think it could be convenient if it was possible to allow for configuring the script to use ´alass´ when syncing against a subtitle and ´ffsubsync´ when syncing against audio. Alternatively, the script could simply ask for which engine to use when run, but I can imagine that would clutter up the UI and be annoying for people who want to configure once and be done with it.

**Comment by tatsumoto-ren** [comment]
I've implemented a menu that allows the user to choose between engines right before synchronizing. See [this branch](https://github.com/Ajatt-Tools/autosubsync-mpv).

**Comment by joaquintorres** [comment]
I've made the v0.32 branch the main branch of the project so that people will be redirected there instead of master, which is only for deprecated versions of mpv. I hope this makes it easier for issues and suggestions to go towards the branch in active development.

**Comment by tatsumoto-ren** [comment]
Great, thank you! Would be nice if the v0.33 branch was the default though because mpv v0.33 was released quite a few months ago.

**Comment by lionslancer** [comment]
Looks good! Thanks for the shoutout on your announcement page too! I was having some issues with the update initially because I simply replaced `autosubsync.lua` in the root of the script folder with the new version, but it clicked once I read the example git command properly. Still, it may be worth explicitly telling people to place both `.lua` files in a subfolder.

I could also see the new functionality having good synergy with being able to set a preferred engine per method as it would allow for very flexible configuration, such as:
```
audio_sync_tool=ask
internal_sub_sync_tool=alass
external_sub_sync_tool=ffsubsync    <= If implemented in the future.
```

**Comment by tatsumoto-ren** [comment]
There are basically two ways to install any mpv add-on. The first one is to place a *lua file to `~/.config/mpv/scripts`. This will only work if the add-on is one file. The second one is to place a folder to `~/.config/mpv/scripts`. The folder should have a file named `main.lua` for this method to work.

**Comment by lionslancer** [comment]
I see now that this stated in the mpv documentation. It was my first time seeing an mpv add-on consisting of multiple files, didn't realize it was standard practice. My mistake.
